### ISSUE TITLE
Plantilla de tesis de magíster

### ISSUE THREAD

**Issue by pzuritas** [open-source-uc/latex-templates#12]
Hace unos meses estaba disponible la plantilla de LaTeX para tesis de magíster en ciencias de la ingeniería, y ahora me parece que no está. Por qué se sacó?

Se podría subir de nuevo?

**Comment by FarDust** [comment]
Creo que la plantilla que buscas está en https://github.com/open-source-uc/latex-template-msc

En #1 se converso porque hay plantillas que están separadas, pero al parecer no agregamos la de MSC.

**Comment by pzuritas** [comment]
Efectivamente, es esa. Agradecido, confundido y agradecido nuevamente con osuc.
