### ISSUE TITLE
Plantilla Ipre

### ISSUE THREAD

**Issue by clangoi** [open-source-uc/latex-templates#20]
Holi, existe la posibilidad de desarrollar una plantilla como las que tienen para un informe iPre?
He usado el formato en word que entrega la plataforma, pero es horrible, y por ejemplo para agregar cosas de código también se pone bien feo.
Eso creo que no hay mucho más que explicar.
Gracias.

**Comment by diegocostares** [comment]
@clangoi No encontré el enunciado del informe de las iPre, me podrías indicar donde esta o adjuntar de algun modo?

**Comment by diegocostares** [comment]
@clangoi Buenas noticias! Tuve una reunión con la coordinadora de las iPres y les gusto la idea, voy a crear una plantilla y compartirla a la iPre para ver si la aprueban.
