### ISSUE TITLE
Formato incorrecto de la plantilla Practica I

### ISSUE THREAD

**Issue by kovaxis** [open-source-uc/latex-templates#23]
Use la plantilla para la Práctica I y me la objetaron por formato: por los márgenes y el interlineado. No se sobre el interlineado, pero a segunda vista los márgenes se ven simétricos, y debieran ser de 3cm y 2.5cm a la izquierda y derecha.

**Comment by diegocostares** [comment]
@negamartin Uh lo siento mucho, el formato anterior era así y a inicios de mayo hicieron esta PR #19 que lo resuelve.

**Comment by kovaxis** [comment]
Me alegro que esté arreglado. Esta arreglado ya el interlineado tambien? Quizas seria bueno agregar un disclaimer que sugiera chequear contra un documento en word que siga el formato, para alertar a la gente credula como yo jajajaajaj

**Comment by diegocostares** [comment]
El interlineado está en 1.5, creo que ese siempre estuvo bien

**Comment by kovaxis** [comment]
En mi experiencia no estaba bien, porque el interlineado se define como 1.5 en word, y el interlineado en word es cualquier cosa. Tuve que hacer una especie de busqueda binaria con prueba y error para encontrar el numero correcto en latex que emula interlineado 1.5 en word.

**Comment by diegocostares** [comment]
En `main.tex` hay una linea que define el interlineado de forma global en 1.5, específicamente:
```text
\setstretch{1.15}
```
